### ISSUE TITLE
Incorrectly raises ValueError.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyperframe#33]
Encountered the following traceback while fuzzing hyper-h2:

```python
Traceback (most recent call last):
  File "script.py", line 10, in <module>
    c.receive_data(sys.stdin.read())
  File "/Users/cory/tmp/fuzz-results/env/lib/python2.7/site-packages/h2/connection.py", line 891, in receive_data
    for frame in self.incoming_buffer:
  File "/Users/cory/tmp/fuzz-results/env/lib/python2.7/site-packages/h2/frame_buffer.py", line 159, in next
    f.parse_body(memoryview(self.data[9:9+length]))
  File "/Users/cory/tmp/fuzz-results/env/lib/python2.7/site-packages/hyperframe/frame.py", line 463, in parse_body
    raise ValueError()
```

It would be a lot better if this exception was not a ``ValueError``.

**Comment by Lukasa** [comment]
Also this one:

```python
Traceback (most recent call last):
  File "script.py", line 10, in <module>
    c.receive_data(sys.stdin.read())
  File "/Users/cory/tmp/fuzz-results/env/lib/python2.7/site-packages/h2/connection.py", line 891, in receive_data
    for frame in self.incoming_buffer:
  File "/Users/cory/tmp/fuzz-results/env/lib/python2.7/site-packages/h2/frame_buffer.py", line 159, in next
    f.parse_body(memoryview(self.data[9:9+length]))
  File "/Users/cory/tmp/fuzz-results/env/lib/python2.7/site-packages/hyperframe/frame.py", line 313, in parse_body
    raise ValueError()
ValueError
```
